version: '3'
services:
  squirrel-pc-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - squirrel-sp-server_db

networks:
  squirrel-sp-server_db: