version: '3'
services:
  squirrel-pc-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - springboot-server_db

networks:
  springboot-server_db:
    external: true